### PR TITLE
fix: recreate netty event loop on restart

### LINKED ISSUE #20: Changing the bindHostname value does not bind to the correct IP address until the component is restarted
**Describe the bug**
The `bindHostname` parameter allows the user to bind the local debug console to an IP other than `127.0.0.1`. But when `bindHostname` is set to `0.0.0.0` and the component is redeployed it does not listen on the new IP address until the component (or Greengrass) is restarted.

**To Reproduce**
- Deploy Greengrass with the local debug console and set the `httpsEnabled` configuration value to `false`
- Get the debug password and connect to the UI to validate it is working
- Revise the deployment in the console and add the `bindHostname` configuration value set to `0.0.0.0`
- Get the debug password and attempt to connect to the UI again

**Expected behavior**
The UI should reload on the new IP address

**Actual behavior**
The UI does not reload on the new IP address. If I look at netstat before setting `bindHostname` to `0.0.0.0` I see this:

```
$ netstat -an | grep 144
tcp6       0      0 127.0.0.1:1441          :::*                    LISTEN
tcp6       0      0 127.0.0.1:1442          :::*                    LISTEN
```

After setting `bindHostname` to `0.0.0.0` and redeploying I see this:

```
$ netstat -an | grep 144
tcp6       0      0 :::1442                 :::*                    LISTEN
```

It appears that both listeners close on `127.0.0.1` but only the listener for port 1442 re-opens on `0.0.0.0`.

After restarting Greengrass it looks like this:

```
$ netstat -an | grep 144
tcp6       0      0 :::1441                 :::*                    LISTEN
tcp6       0      0 :::1442                 :::*                    LISTEN
```

**Environment**
 - OS: Ubuntu 20.04 LTS
 - JDK version: openjdk 17.0.2
 - Nucleus version: 2.5.5
 - LocalDebugConsole version: 2.2.3

**Additional context**
This bug causes issues when changing the `bindHostname` configuration value without restarting.

Setting `bindHostname` to `0.0.0.0` is useful testing and developing Greengrass code inside of virtual machines. Some virtualization software (like Vagrant with VirtualBox) can't forward connections if the socket is only bound to `127.0.0.1`.

### PR DESCRIPTION
**Pull request by MikeDombo**
**Issue #, if available:**

**Description of changes:**

**Why is this change necessary:**

Fixes #20.

**How was this change tested:**

Ran on mac and verified that without this change we do not run the Netty server on the new hostname.

**Any additional information or context required to review the change:**

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/main/js/dashboard-frontend/src/components/details/ConfigEditor.tsx [hunk 1]
```diff
@@ -162,19 +145,13 @@ export class ConfigEditor extends React.Component<
...
       .then((component) =>
         SERVER.sendRequest({ call: APICall.getConfig, args: [component.name] })
       )
       .then((config) => {
         if (config.successful) {
           this.setState({ value: config.yaml });
-          if (this.state.service.origin === USER_CREATED) {
-            this.setState({ allowEdit: true });
-          }
+          this.setState({ allowEdit: true });
```
Comment (rbattle) [inline src/main/js/dashboard-frontend/src/components/details/ConfigEditor.tsx:154]: what's the context behind this change?

Comment (MikeDombo) [reply src/main/js/dashboard-frontend/src/components/details/ConfigEditor.tsx:154]: We didn't allow you to edit the configuration for components that weren't considered user created, which was always silly. It is especially annoying when using plugins in the trusted plugin directory because those weren't considered to be user created, so you couldn't change the config. 

Without this change you could view and control any service, you just couldn't edit the config using the console. But in order to be truly useful and powerful, we should let you change the configuration too.

Comment (rbattle) [reply src/main/js/dashboard-frontend/src/components/details/ConfigEditor.tsx:154]: I agree with the change, but could you make a separate PR for it since it's not related to the netty event loop problem?

Comment (MikeDombo) [reply src/main/js/dashboard-frontend/src/components/details/ConfigEditor.tsx:154]: #22

**Review by junfuchen99 — APPROVED** [review]

**Review by rbattle — APPROVED** [review]
